import {
  Ban,
  Building,
  Calculator,
  CircleQuestionMark,
  DatabaseBackup,
  FileText,
  House,
  Layers,
  LayoutGrid,
  Mail,
  MessageCircleMore,
  Phone,
  RulerDimensionLine,
  ShieldCheck,
  ShieldClose,
  SlidersHorizontal,
  UserLock,
  UserRoundPen,
} from "lucide-react";
import type { SidebarItemType } from "./sidebarConfig";

export const settingsSidebarItems: SidebarItemType[] = [
  {
    type: "accordion",
    label: "Main Settings",
    icon: SlidersHorizontal,
    items: [
      { label: "General Settings", to: "/settings/general-settings" },
      { label: "Currency", to: "/settings/currency" },
      { label: "Company Logo", to: "/settings/company-logo" },
      { label: "Cron Job Settings", to: "/settings/cron-job-settings" },
      { label: "Tax Rates", to: "/settings/tax-rates" },
      { label: "Modules", to: "/settings/modules" },
    ],
  },
  {
    type: "link",
    label: "Stages",
    to: "/settings/stages",
    icon: Layers,
  },
  {
    type: "link",
    label: "Sections",
    to: "/settings/sections",
    icon: LayoutGrid,
  },
  {
    type: "link",
    label: "User Roles",
    to: "/settings/user-role",
    icon: UserLock,
  },
  {
    type: "link",
    label: "Weird People",
    to: "/settings/weird-people",
    icon: ShieldClose,
  },
  {
    type: "link",
    label: "Declaration Form",
    to: "/settings/declaration-form",
    icon: FileText,
  },
  {
    type: "link",
    label: "Category",
    to: "/settings/category",
    icon: House,
  },
  {
    type: "link",
    label: "Missing Data",
    to: "/settings/missing-data",
    icon: DatabaseBackup,
  },
  {
    type: "link",
    label: "Units Control",
    to: "/settings/units-control",
    icon: RulerDimensionLine,
  },
  {
    type: "accordion",
    label: "Cost Estimation",
    icon: Calculator,
    items: [
      { label: "Region Costs", to: "/settings/region-costs" },
      { label: "Structure Type", to: "/settings/structure-type" },
      { label: "Project Type", to: "/settings/Project-type" },
    ],
  },
  {
    type: "link",
    label: "FAQ Categories",
    to: "/settings/faq-categories",
    icon: CircleQuestionMark,
  },
  {
    type: "link",
    label: "Edit End Users",
    to: "/settings/edit-end-user",
    icon: UserRoundPen,
  },
  {
    type: "link",
    label: "Companies",
    to: "/settings/companies",
    icon: Building,
  },
  {
    type: "link",
    label: "Insurers",
    to: "/settings/insurance-companies",
    icon: ShieldCheck,
  },
  {
    type: "accordion",
    label: "Email",
    icon: Mail,
    items: [
      { label: "Email Settings", to: "/settings/email-settings" },
      { label: "Email Templates", to: "/settings/email-templates" },
      { label: "Email Queue", to: "/settings/email-queue" },
      { label: "Email Log", to: "/settings/email-log" },
    ],
  },
  {
    type: "accordion",
    label: "SMS",
    icon: MessageCircleMore,
    items: [
      { label: "SMS Settings", to: "/settings/sms-settings" },
      { label: "SMS Templates", to: "/settings/sms-templates" },
      { label: "SMS Queue", to: "/settings/sms-queue" },
      { label: "SMS Log", to: "/settings/sms-log" },
    ],
  },
  {
    type: "accordion",
    label: "Whats App",
    icon: Phone,
    items: [
      { label: "Whats App Settings", to: "/settings/whatsApp-settings" },
      { label: "Whats App Templates", to: "/settings/whatsApp-templates" },
      { label: "Whats App Queue", to: "/settings/whatsApp-queue" },
      { label: "Whats App Log", to: "/settings/whatsApp-log" },
    ],
  },
  {
    type: "accordion",
    label: "Suspend Settings",
    icon: Ban,
    items: [
      { label: "Suspend Filters", to: "/settings/suspend-filters" },
      { label: "Suspended Projects", to: "/settings/suspended-projects" },
    ],
  },
];
